---
title: "Module_14&15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(curl)
library(ggplot2)
library(dplyr)
library(car)
```

#Module 14
```{r}
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/zombies.csv")
z <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = TRUE)
class(z$gender)
summary(z$gender)
plot(z$height ~ z$gender)

m <- lm(data = z, height ~ gender)
summary(m)

levels(z$gender)

z$gender <- relevel(z$gender, ref = "Male")
m <- lm(data = z, height ~ gender)
summary(m)

p <- 1 - pf(276.9, df1 = 1, df2 = 998)
p

z$occupation <- "temp"
unique(z$major)
levels(z$major)
row(data.frame(levels(z$major)))

z$occupation[row(data.frame(levels(z$major))) %in% c(1, 2, 3, 5, 6, 14, 15,
    16, 18, 21, 23)] <- "natural science"
z$occupation[row(data.frame(levels(z$major))) %in% c(7, 8, 12, 17, 19, 22)] <- "logistics"
z$occupation[row(data.frame(levels(z$major))) %in% c(4, 18, 20)] <- "engineering"
z$occupation[row(data.frame(levels(z$major))) %in% c(9, 10, 11, 13, 24, 25,
    26)] <- "other"
z$occupation <- as.factor(z$occupation)
levels(z$occupation)

z$occupation <- relevel(z$occupation, ref = "natural science")
levels(z$occupation)

plot(data = z, zombies_killed ~ occupation)
```